# Image is being built in Gitlab runners, pushed to the Openshift registry and in the end the DeploymentConfig is updated to trigger a new deployment
stages:
- test
- package
- buildimage
- deploy

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  OPENSHIFT_SERVER: 192.168.64.3
  DOCKER_REGISTRY: 172.30.1.1:5000

cache:
  paths:
    - .m2/repository

# execute unit tests
unit-tests:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
    - ./mvnw clean test

# create the .jar file
package:
  image: openjdk:8-jdk-alpine
  stage: package
  script:
    - ./mvnw -DskipTests clean package
  artifacts:
    paths:
      - target/oc-example-*.jar

# create the docker image and push the image to the Openshift registry
docker:
  image: docker:latest
  stage: buildimage
  services:
    - docker:dind
  script:
    - export DOCKER_TLS_VERIFY="1"
    - export DOCKER_HOST="tcp://192.168.64.3:2376"
    - export DOCKER_CERT_PATH="openshift/certs"
    - docker login -u developer -p 5bglDnnHIXVkVQg-rVUnStM6InTR9oZ2rxCmADDFF-I $DOCKER_REGISTRY
    - docker build -t "$DOCKER_REGISTRY/oc-example-build-git/oc-example:${CI_COMMIT_SHA:0:8}" .
    - docker push "$DOCKER_REGISTRY/oc-example-build-git/oc-example:${CI_COMMIT_SHA:0:8}"

# deploy the image to the console - change the DC
deploy:
  image: michelesr/oc
  stage: deploy
  script:
    - oc login https://192.168.64.3:8443 -u developer -p any --insecure-skip-tls-verify=true
    - oc project oc-example-build-git
    - oc get dc oc-example -o json > /tmp/oc-example.json
    - sed -i -E "s/oc-example:.*/oc-example:${CI_COMMIT_SHA:0:8}\"/g" /tmp/oc-example.json
    - oc replace -f /tmp/oc-example.json

