apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-example-deployment
  labels:
    app: oc-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-example
  template:
    metadata:
      labels:
        app: oc-example
    spec:
      containers:
      - name: oc-example
        image: danielh1307/oc-example:0.0.1-SNAPSHOT
        env:
        - name: EARLY_ADOPTER
          value: "no"
        - name: ADMIN_NAME
          valueFrom:
            configMapKeyRef:
              name: oc-config
              key: admin.name
        - name: ADMIN_PW
          valueFrom:
            configMapKeyRef:
              name: oc-config
              key: admin.pw
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3