apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oc-example-deployment-ea
  labels:
    app: oc-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-example
  template:
    metadata:
      labels:
        app: oc-example
    spec:
      containers:
      - name: oc-example
        image: us.gcr.io/my-oc-203309/oc-example:0.0.2-SNAPSHOT
        env:
        - name: EARLY_ADOPTER
          value: "yes"
        - name: ADMIN_NAME
          valueFrom:
            configMapKeyRef:
              name: oc-config
              key: admin.name
        - name: ADMIN_PW
          valueFrom:
            configMapKeyRef:
              name: oc-config
              key: admin.pw
        ports:
        - containerPort: 8080